//Conexión de los pines referentes a los displays TM1637Display
#define DSPLAY_CLOCK 12
#define DISPLAY1_PIN 2
#define DISPLAY2_PIN 3
#define DISPLAY3_PIN 4
#define DISPLAY4_PIN 5
#define DISPLAY5_PIN 6
#define DISPLAY6_PIN 7

#define BOMB_NEOPIXEL_STRIP_PIN 14
#define BOMB_NEOPIXEL_STRIP_LED_COUNT 20

#define HEALTH_NEOPIXEL_STRIP_PIN 11
#define HEALTH_NEOPIXEL_STRIP_LED_COUNT 20

#define AMMO_NEOPIXEL_STRIP_PIN 10
#define AMMO_NEOPIXEL_STRIP_LED_COUNT 20
