
#define BOMB_NEOPIXEL_STRIP_PIN 2
#define BOMB_NEOPIXEL_STRIP_LED_COUNT 20

#define HEALTH_NEOPIXEL_STRIP_PIN 3
#define HEALTH_NEOPIXEL_STRIP_LED_COUNT 20

#define ARMOR_NEOPIXEL_STRIP_PIN 4
#define ARMOR_NEOPIXEL_STRIP_LED_COUNT 20

#define AMMO_NEOPIXEL_STRIP_PIN 5
#define AMMO_NEOPIXEL_STRIP_LED_COUNT 20

#define ROUND_PERCENT_SCORE_NEOPIXEL_STRIP_PIN 6
#define ROUND_PERCENT_SCORE_NEOPIXEL_STRIP_LED_COUNT 20
